In [1]:
import numpy as np

In [96]:
gap = 30
# set lookback value 
def combination(data):
    dataset = []
    for idx,value in enumerate(data):
        if(idx<len(data)-gap):
            temp = data[idx:idx+gap]
            temp = temp.reshape(6*gap)
            dataset.append(temp)
    return np.array(dataset)

def get_data():#normlize
    data = np.loadtxt('hk.txt')
    print(data.shape)
    x = combination(data)
    y = data[gap:]
    return x,y

x,y = get_data()

(2280, 6)


In [104]:
# Deep NN with keras
from keras.models import Sequential 
from keras.layers.core import Dense, Dropout
from keras.layers import Embedding,LSTM
from keras import backend as K

def swish(x):   #Activation Function
    return x*K.sigmoid(x)

def get_LSTM():
    model = Sequential()
    model.add(Embedding(6*gap,32))
    model.add(LSTM(512,recurrent_dropout=0.2, dropout=0.2))
    model.add(Dropout(0.2))
    model.add(Dense(256, activation='tanh'))
    model.add(Dropout(0.5))
    model.add(Dense(64, activation='tanh'))
    model.add(Dropout(0.2))
    model.add(Dense(6, activation="sigmoid")) 
    model.summary()
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model        

In [105]:
def get_test():
    data = np.loadtxt('lotto.txt').astype('int8')
    print(data.shape)
    x = combination(data)
    y = data[gap:]
    return x,y 

test_x,test_y = get_test()

(1470, 6)


In [106]:
lstm_model = get_LSTM()
lstm_model.fit(x/50, y/50, batch_size=32, epochs=1,verbose=1)
lstm_result =np.around(lstm_model.predict(test_x/50)*50).astype('int8')

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_15 (Embedding)     (None, None, 32)          5760      
_________________________________________________________________
lstm_15 (LSTM)               (None, 512)               1116160   
_________________________________________________________________
dropout_14 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_30 (Dense)             (None, 256)               131328    
_________________________________________________________________
dropout_15 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_31 (Dense)             (None, 64)                16448     
_________________________________________________________________
dropout_16 (Dropout)         (None, 64)                0         
__________

In [109]:
lstm_model.save('model.h5')

In [107]:
countRd = 0
countTree = 0
countLinear = 0
countDNN = 0
countLSTM = 0

winRd = 0
winTree = 0
winLinear = 0
winDNN = 0
winLSTM = 0

for idx in range(len(test_y)):
    print("------開獎對比----"+str(idx))
    print(lstm_result[idx])
    print(test_y[idx])
    print("-------------------")
    setLSTM = set(lstm_result[idx])
    setWin = set(test_y[idx])
    resultLSTM = setLSTM&setWin

    if(resultLSTM!=set()):
        print('LSTM:',resultLSTM)
        if(len(resultLSTM)>=3):
            print('LSTM 中獎咯')
            winLSTM +=1
        countLSTM += 1

------開獎對比----0
[ 8 15 22 28 36 43]
[13 17 19 26 39 45]
-------------------
------開獎對比----1
[ 8 15 22 28 36 43]
[ 3 11 19 20 22 28]
-------------------
LSTM: {28, 22}
------開獎對比----2
[ 8 15 22 28 36 43]
[22 25 29 31 34 46]
-------------------
LSTM: {22}
------開獎對比----3
[ 8 15 22 28 36 43]
[ 1 10 13 33 34 46]
-------------------
------開獎對比----4
[ 8 15 22 28 36 43]
[ 3  9 13 28 40 48]
-------------------
LSTM: {28}
------開獎對比----5
[ 8 15 22 28 36 43]
[ 6 27 40 44 45 47]
-------------------
------開獎對比----6
[ 8 15 22 28 36 43]
[ 3  4 10 23 25 26]
-------------------
------開獎對比----7
[ 8 15 22 28 36 43]
[ 4 10 11 14 32 36]
-------------------
LSTM: {36}
------開獎對比----8
[ 8 15 22 28 36 43]
[ 2  4 18 20 32 49]
-------------------
------開獎對比----9
[ 8 15 22 28 36 43]
[ 6 28 30 34 43 46]
-------------------
LSTM: {43, 28}
------開獎對比----10
[ 8 15 22 28 36 43]
[ 1 16 17 30 36 49]
-------------------
LSTM: {36}
------開獎對比----11
[ 8 15 22 28 36 43]
[ 6 22 27 34 42 44]
-------------------
LSTM: {22}
-

-------------------
LSTM: {8, 43}
------開獎對比----261
[ 8 15 22 28 36 43]
[ 9 10 12 25 33 38]
-------------------
------開獎對比----262
[ 8 15 22 28 36 43]
[ 1  4  5 15 18 42]
-------------------
LSTM: {15}
------開獎對比----263
[ 8 15 22 28 36 43]
[ 5  7 11 19 36 42]
-------------------
LSTM: {36}
------開獎對比----264
[ 8 15 22 28 36 43]
[ 6  8 29 39 46 49]
-------------------
LSTM: {8}
------開獎對比----265
[ 8 15 22 28 36 43]
[ 6 30 34 45 46 48]
-------------------
------開獎對比----266
[ 8 15 22 28 36 43]
[ 5 18 20 33 38 40]
-------------------
------開獎對比----267
[ 8 15 22 28 36 43]
[12 14 20 22 37 40]
-------------------
LSTM: {22}
------開獎對比----268
[ 8 15 22 28 36 43]
[ 5 17 29 34 38 47]
-------------------
------開獎對比----269
[ 8 15 22 28 36 43]
[ 2 17 28 29 38 49]
-------------------
LSTM: {28}
------開獎對比----270
[ 8 15 22 28 36 43]
[ 6  7 11 19 47 48]
-------------------
------開獎對比----271
[ 8 15 22 28 36 43]
[ 1 23 34 37 43 45]
-------------------
LSTM: {43}
------開獎對比----272
[ 8 15 22 28 36 43]
[14 1

[ 8 15 22 28 36 43]
[ 3  4  8 16 41 43]
-------------------
LSTM: {8, 43}
------開獎對比----667
[ 8 15 22 28 36 43]
[10 14 18 41 42 49]
-------------------
------開獎對比----668
[ 8 15 22 28 36 43]
[ 1  2 19 22 26 44]
-------------------
LSTM: {22}
------開獎對比----669
[ 8 15 22 28 36 43]
[12 13 24 34 35 39]
-------------------
------開獎對比----670
[ 8 15 22 28 36 43]
[ 1 22 35 38 39 45]
-------------------
LSTM: {22}
------開獎對比----671
[ 8 15 22 28 36 43]
[ 2  8 29 36 42 44]
-------------------
LSTM: {8, 36}
------開獎對比----672
[ 8 15 22 28 36 43]
[ 3  4 19 22 32 40]
-------------------
LSTM: {22}
------開獎對比----673
[ 8 15 22 28 36 43]
[ 8 12 23 37 38 48]
-------------------
LSTM: {8}
------開獎對比----674
[ 8 15 22 28 36 43]
[14 16 21 32 35 43]
-------------------
LSTM: {43}
------開獎對比----675
[ 8 15 22 28 36 43]
[ 3 11 14 39 41 48]
-------------------
------開獎對比----676
[ 8 15 22 28 36 43]
[ 8  9 10 20 31 40]
-------------------
LSTM: {8}
------開獎對比----677
[ 8 15 22 28 36 43]
[ 1 11 20 28 30 46]
----------

LSTM: {8, 22, 15}
LSTM 中獎咯
------開獎對比----1097
[ 8 15 22 28 36 43]
[18 35 36 41 47 49]
-------------------
LSTM: {36}
------開獎對比----1098
[ 8 15 22 28 36 43]
[10 14 19 24 35 37]
-------------------
------開獎對比----1099
[ 8 15 22 28 36 43]
[17 18 40 41 45 47]
-------------------
------開獎對比----1100
[ 8 15 22 28 36 43]
[ 1 11 19 24 26 28]
-------------------
LSTM: {28}
------開獎對比----1101
[ 8 15 22 28 36 43]
[ 9 10 14 20 36 47]
-------------------
LSTM: {36}
------開獎對比----1102
[ 8 15 22 28 36 43]
[ 2 11 20 32 33 36]
-------------------
LSTM: {36}
------開獎對比----1103
[ 8 15 22 28 36 43]
[14 28 31 38 42 44]
-------------------
LSTM: {28}
------開獎對比----1104
[ 8 15 22 28 36 43]
[ 1 17 20 36 37 45]
-------------------
LSTM: {36}
------開獎對比----1105
[ 8 15 22 28 36 43]
[ 5 16 25 32 37 44]
-------------------
------開獎對比----1106
[ 8 15 22 28 36 43]
[ 2  8 10 14 27 49]
-------------------
LSTM: {8}
------開獎對比----1107
[ 8 15 22 28 36 43]
[ 3 20 30 35 38 41]
-------------------
------開獎對比----1108
[ 8 15 22

In [108]:
print("--------",gap,"----------")
print('model','hit','win')
print('LSTM',countLSTM,winLSTM)

-------- 30 ----------
model hit win
LSTM 880 41
